### PR TITLE
When run Tania Core on Portainer

### PR DESCRIPTION
**Pull request by jhonatas-mendes**
Hi, I inserted commit to when run on Portainer too. Cheers to all team

### CODE REVIEW

**Comment by jhonatas-mendes** [comment]
I inserted some lines about when to run Tania Core on Portainer  with Docker too.

**Comment by bepitulaz** [comment]
Thanks, @jhonatas-mendes. I'll review it soon.

**Comment by wotnak** [comment]
This change in readme may be a bit confusing and probably should be updated or removed. The title says "Run Tania Core..." but the given example docker-compose/portainer configuration uses legacy php based tania version https://github.com/usetania/tania and not the current one from this repo.

**Comment by bepitulaz** [comment]
The new Readme will be updated in this PR: https://github.com/usetania/tania-core/pull/135

**Comment by jhonatas-mendes** [comment]
> The new Readme will be updated in this PR: #135

Thanks friend for including this contribution more.

**Pull request merged**
